#!sh
repo=`git remote  -v|awk '{print $2}'`
host=`echo $repo|sed 's/:.*//g'`
repodir=`echo $repo|sed 's/.*://g'`
ssh $host "cd $repodir; git fetch; git reset --hard origin/master"
git push && \
ssh $host "cd $repodir; git fetch; git reset --hard;cd deploy;./$repodir deploy"
