#!sh
repo=`git remote  -v|awk '{print $2}'`
host=`echo $repo|sed 's/:.*//g'`
repodir=`echo $repo|sed 's/.*://g'`
sh ~/gitbin/pushme.sh && \
ssh $host "cd $repodir; git push;/opt/tiger/deploy/pushtest"
